// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANIfLFo70iK5tBUfNDf9NFBUbBRsLppBk',
    appId: '1:883982055095:web:525a2ebf6376de8360ff32',
    messagingSenderId: '883982055095',
    projectId: 'expenseapp-e617c',
    authDomain: 'expenseapp-e617c.firebaseapp.com',
    storageBucket: 'expenseapp-e617c.firebasestorage.app',
    measurementId: 'G-8V293KXEFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMuR3Sg_wxAoULPRkY83kiZHfKEtfNpkc',
    appId: '1:883982055095:android:9efcfe296ccf0e7f60ff32',
    messagingSenderId: '883982055095',
    projectId: 'expenseapp-e617c',
    storageBucket: 'expenseapp-e617c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJgr6pKipPOsLBpQgiCKGHs2l5buVXUro',
    appId: '1:883982055095:ios:e70de5da032adb1160ff32',
    messagingSenderId: '883982055095',
    projectId: 'expenseapp-e617c',
    storageBucket: 'expenseapp-e617c.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerApp',
  );
}
